import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import { db } from "@/lib/db";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const DEFAULT_LOGO = "https://i.imgur.com/USEEiyC.png";

export async function generateMetadata(): Promise<Metadata> {
  let logoUrl = DEFAULT_LOGO;
  try {
    const setting = await db.siteSetting.findUnique({ where: { key: "LOGO_URL" } });
    if (setting?.value) logoUrl = setting.value;
  } catch {
    // DB unavailable — use default
  }

  return {
    metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "https://chebbitrade.com"),
    title: "Chebbi Trading — Signaux Forex Gratuits | Partenaire XM",
    description:
      "Chebbi Trading - Signaux Forex GRATUITS. 4 ans de résultats live sur YouTube. Inscrivez-vous sur XM et rejoignez notre groupe.",
    keywords: [
      "Chebbi Trading",
      "Forex",
      "Signaux Forex",
      "Trading Gratuit",
      "XM",
      "XAUUSD",
      "Or",
      "Live YouTube",
    ],
    icons: {
      icon: logoUrl,
    },
    openGraph: {
      title: "Chebbi Trading - Signaux Forex Gratuits",
      description:
        "4 ans de résultats live. Rejoignez notre groupe gratuit en ouvrant un compte XM.",
      siteName: "Chebbi Trading",
      type: "website",
      // images auto-generated by opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      // images auto-generated by twitter-image.tsx
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="dark" suppressHydrationWarning>
      <head>
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='light'){document.documentElement.classList.remove('dark')}else{document.documentElement.classList.add('dark')}}catch(e){document.documentElement.classList.add('dark')}})()`,
          }}
        />
      </head>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
